#include "../../include_files/ti83plus.inc"
.org $9D93
.db $BB, $6D
; This MUST be the first actual instruction
    jp _main
; Include the code generated by the C compiler
#include "output/main_c.asm"

; Include your manual functions
#include "src/functions.asm"