# ----------------------------
# Makefile Options
# ----------------------------

NAME = Caeser_Cipher
ICON = icon.png
DESCRIPTION = "Simple Caeser Encryption and Decryption"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
